# Generated by Django 5.1.2 on 2025-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
